#!/usr/bin/env python3
"""Generate docs/api-reference/cli.md from the CLI itself.

The reference page used to be written by hand and had drifted badly from the
code: it documented options that never existed (``manifest keygen --print-pub``,
``manifest verify --min-slsa-level``) and omitted the ones that do. Rendering it
from click's own help text means the page cannot describe a flag the CLI does
not have.

Run from the repository root:

    python scripts/gen_cli_reference.py

``tests/test_cli_reference.py`` regenerates the page in memory and fails if the
committed copy differs, so CI catches a CLI change that was not reflected in the
docs. Regenerate and commit the result whenever the command surface changes.
"""
from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT / "python" / "src"))

import click  # noqa: E402

from agent_manifest.cli import TOP_LEVEL_COMMANDS, cli  # noqa: E402

OUTPUT_PATH = REPO_ROOT / "docs" / "api-reference" / "cli.md"

HEADER = """<!-- Generated by scripts/gen_cli_reference.py. Do not edit by hand. -->

# CLI reference

The `manifest` command is installed with the `cli` extra.

```bash
pip install "agent-manifest[cli]"
```

Every command is invoked directly: `manifest verify signed.json`. Releases up to
0.5.0 nested them under a second `manifest` group; that spelling still works and
prints a deprecation warning.

## Commands
"""

FOOTER = """## Source

::: agent_manifest.cli
"""


def _help_text(name: str) -> str:
    command = cli.commands[name]
    ctx = click.Context(command, info_name=f"manifest {name}", terminal_width=88)
    return command.get_help(ctx).rstrip()


def render() -> str:
    sections = [HEADER]
    for name in TOP_LEVEL_COMMANDS:
        summary = (cli.commands[name].help or "").strip().splitlines()[0]
        sections.append(f"\n### manifest {name}\n\n{summary}\n\n```\n{_help_text(name)}\n```\n")
    sections.append("\n" + FOOTER)
    return "".join(sections)


def main() -> None:
    OUTPUT_PATH.write_text(render(), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(REPO_ROOT)} ({len(TOP_LEVEL_COMMANDS)} commands)")


if __name__ == "__main__":
    main()
