"""The committed CLI reference page must match the CLI it documents.

``docs/api-reference/cli.md`` is generated by ``scripts/gen_cli_reference.py``.
Before it was generated it had drifted far enough to document options that never
existed (``manifest keygen --print-pub``, ``manifest verify --min-slsa-level``).
This test regenerates the page in memory and fails if the committed copy differs,
so a change to a command or an option cannot land with stale docs.

To fix a failure here, run from the repository root:

    python scripts/gen_cli_reference.py

and commit the result.
"""
from __future__ import annotations

import importlib.util
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
GENERATOR = REPO_ROOT / "scripts" / "gen_cli_reference.py"
REFERENCE = REPO_ROOT / "docs" / "api-reference" / "cli.md"


def _load_generator():
    # Absent when the tests run from an sdist, which ships src/ and tests/ only.
    if not GENERATOR.is_file():
        pytest.skip("generator not present (running outside a source checkout)")
    spec = importlib.util.spec_from_file_location("gen_cli_reference", GENERATOR)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_cli_reference_matches_the_cli():
    generator = _load_generator()
    if not REFERENCE.is_file():
        pytest.skip("reference page not present")

    expected = generator.render()
    actual = REFERENCE.read_text(encoding="utf-8")

    assert actual == expected, (
        "docs/api-reference/cli.md is out of date with the CLI. "
        "Run: python scripts/gen_cli_reference.py"
    )


def test_reference_documents_every_command():
    generator = _load_generator()
    rendered = generator.render()

    for name in generator.TOP_LEVEL_COMMANDS:
        assert f"### manifest {name}" in rendered
        # The usage line proves the command is reachable without a group prefix.
        assert f"Usage: manifest {name}" in rendered
